### ISSUE TITLE
Turbulent_Flame not accepting FlameMaster File for main simulation

### ISSUE THREAD

**Issue by himakarganti** [pencil-code/pencil-code#33]
I am trying to run a 3D turbulent_flame case with modified chemistry, and was able to figure out the how to make the mechanism work with Pencil-Code. I was able to run the turbulent box and the 3d initial conditions for the simulation. I was having a problem with the laminar flame solution from Pencil code using the RK3 & RKF time-marching scheme for the mechanism I am using - the solution oscillates very badly and crashes, and I cant go down any lower on the time-step size (~1e-15). Hence I tried to generated the Flame solution with FlameMaster which is accepted by Pencil-Code. 
This is a high priority for my work and I appreciate any help I can get to get this going. However, I am running into the following issue when trying to run the main simulation:
A bunch of the following:

**_Error termination. Backtrace:
At line 6051 of file chemistry.f90 (unit = 1, file = 'H2_p01_0phi0_7000tu0300')
Fortran runtime error: Bad real number in item 259 of list input_**

followed by:

**_Error termination. Backtrace:
 init_lnrho: nothing
 init_lnrho: cs2bot,cs2top=   1.0000000000000000        1.0000000000000000     
 init_energy: nothing
 Reading initial conditions in file H2_p01_0phi0_7000tu0300
At line 6051 of file chemistry.f90 (unit = 1, file = 'H2_p01_0phi0_7000tu0300')
Fortran runtime error: Bad real number in item 259 of list input_**

and then by:

**_#0  0x7fb5b034ad18 in read_real
	at ../.././libgfortran/io/list_read.c:2026
#1  0x7fb5b034ca7d in list_formatted_read_scalar
	at ../.././libgfortran/io/list_read.c:2179
#2  0x411655 in ???
#3  0x42893f in ???
#4  0x650413 in ???
#5  0x650d11 in ???
#6  0x7fb5af4af3d4 in ???
#7  0x403168 in ???
#8  0xffffffffffffffff in ???
#0  0x7f0a024b0d18 in read_real
	at ../.././libgfortran/io/list_read.c:2026
#1  0x7f0a024b2a7d in list_formatted_read_scalar_**

and this keeps going on for the 64 cores I am trying to use. I am sure it is not an encoding issue. My FlameMaster file is:
[FM.zip](https://github.com/pencil-code/pencil-code/files/3061856/FM.zip)

Can someone please please help me get main simulation running?

**Comment by himakarganti** [comment]
The FlameMaster file had a couple of errors - it now runs once they were fixed.
